# fly.toml app configuration file generated for cursor-api on 2025-03-14T11:43:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cursor-api'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
